version: '3.8'

services:
<<<<<<< HEAD
=======
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: samandar
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
>>>>>>> refs/remotes/origin/main
  web:
    build: .
    command: ["gunicorn", "HealthTrackAPI.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=healthtrack
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
<<<<<<< HEAD

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_NAME=healthtrack
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    
  
volumes:
  postgres_data:
    
=======
    environment:
      DB_NAME: postgres
      DB_USER: samandar
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
>>>>>>> refs/remotes/origin/main
