version: '3'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: samandar
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_USER: samandar
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
